### ISSUE TITLE
build failed - error E0423

### ISSUE THREAD

**Issue by randomsymbols** [webchain-network/webchain-cli#3]
`cargo build --release`

gives this error:

error[E0423]: expected function, tuple struct or tuple variant, found struct ast::Name
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.58.1/src/symbol.rs:146:27
    |
146 |                       name: ast::Name($index),
    |                             ^^^^^^^^^
...
165 | / declare_keywords! {
166 | |     // Invalid identifier
167 | |     (0,  Invalid,        "")
168 | |
...   |
231 | |     (56, CrateRoot, "{{root}}")
232 | | }
    | |_- in this macro invocation

   Compiling hpack v0.2.0
error: aborting due to previous error

For more information about this error, try rustc --explain E0423.
error: could not compile syntex_syntax.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by danielwebimp** [comment]
This error should have been already fixed on the previous release.
